
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int DERECHA_CORCHETE = 53;
  public static final int MULT = 33;
  public static final int CONST = 8;
  public static final int CHAR = 3;
  public static final int PUNTO_Y_COMA = 54;
  public static final int INPUT = 22;
  public static final int CASE = 17;
  public static final int RESTA = 32;
  public static final int DOS_PUNTOS = 56;
  public static final int CONTINUE = 10;
  public static final int INT = 2;
  public static final int FOR = 11;
  public static final int NOT = 46;
  public static final int AND = 44;
  public static final int MENORIGUAL = 40;
  public static final int IDENTIFICADOR = 26;
  public static final int DERECHA_PAREN = 49;
  public static final int IZQ_PAREN = 48;
  public static final int OR = 45;
  public static final int IGUALDAD = 38;
  public static final int BOOL = 5;
  public static final int DIV = 34;
  public static final int INCREMENTO = 36;
  public static final int SUMA = 31;
  public static final int DERECHA_LLAVE = 51;
  public static final int MAIN = 24;
  public static final int IF = 14;
  public static final int IZQ_LLAVE = 50;
  public static final int MAYORIGUAL = 41;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int TRUE = 20;
  public static final int DECREMENTO = 37;
  public static final int error = 1;
  public static final int COMA = 55;
  public static final int LITERAL_CHAR = 29;
  public static final int MENOR = 42;
  public static final int MOD = 35;
  public static final int BREAK = 9;
  public static final int VOID = 7;
  public static final int LITERAL_FLOAT = 28;
  public static final int ASIGNACION = 47;
  public static final int SWITCH = 16;
  public static final int MAYOR = 43;
  public static final int LITERAL_INT = 27;
  public static final int ELSE = 15;
  public static final int DESIGUALDAD = 39;
  public static final int LITERAL_STRING = 30;
  public static final int IZQ_CORCHETE = 52;
  public static final int WHILE = 12;
  public static final int DEFAULT = 18;
  public static final int FLOAT = 4;
  public static final int LEN = 25;
  public static final int STRING = 6;
  public static final int FALSE = 21;
  public static final int PRINT = 23;
  public static final int DO = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "CHAR",
  "FLOAT",
  "BOOL",
  "STRING",
  "VOID",
  "CONST",
  "BREAK",
  "CONTINUE",
  "FOR",
  "WHILE",
  "DO",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "RETURN",
  "TRUE",
  "FALSE",
  "INPUT",
  "PRINT",
  "MAIN",
  "LEN",
  "IDENTIFICADOR",
  "LITERAL_INT",
  "LITERAL_FLOAT",
  "LITERAL_CHAR",
  "LITERAL_STRING",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "MOD",
  "INCREMENTO",
  "DECREMENTO",
  "IGUALDAD",
  "DESIGUALDAD",
  "MENORIGUAL",
  "MAYORIGUAL",
  "MENOR",
  "MAYOR",
  "AND",
  "OR",
  "NOT",
  "ASIGNACION",
  "IZQ_PAREN",
  "DERECHA_PAREN",
  "IZQ_LLAVE",
  "DERECHA_LLAVE",
  "IZQ_CORCHETE",
  "DERECHA_CORCHETE",
  "PUNTO_Y_COMA",
  "COMA",
  "DOS_PUNTOS"
  };
}

