package lexer;

public enum Tokens {
    INT, CHAR, FLOAT, BOOL, STRING,
    VOID, CONST, BREAK, CONTINUE,
    FOR, WHILE, DO, IF, ELSE,
    SWITCH, CASE, DEFAULT, RETURN, TRUE,
    FALSE, INPUT, PRINT, MAIN, LEN,
    IDENTIFICADOR,
    LITERAL_INT,
    LITERAL_FLOAT,
    LITERAL_CHAR,
    LITERAL_STRING,
    SUMA, RESTA, MULT, DIV, MOD,
    INCREMENTO, DECREMENTO,
    IGUALDAD, DESIGUALDAD,
    MENORIGUAL, MAYORIGUAL,
    MENOR, MAYOR,
    AND, OR, NOT,
    ASIGNACION,
    IZQ_PAREN, DERECHA_PAREN,
    IZQ_LLAVE, DERECHA_LLAVE,
    IZQ_CORCHETE, DERECHA_CORCHETE,
    PUNTO_Y_COMA, COMA, DOS_PUNTOS,
    COMENTARIO_BLOQUE, COMENTARIO_LINEA,
    ERROR;
}
